config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "contacts#index" , as: 'home'
  resources :contacts


  get 'about' => 'pages#about'
  get 'contactus' => 'pages#contactus'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :firstname, presence: true , length: { minimum: 3 ,maximum: 15 }
    validates :lastname, presence: true , length: { minimum: 4}
    validates :email, presence: true  ,   length: { within: 5..50 },uniqueness: true ,format: URI::MailTo::EMAIL_REGEXP
    validates :contactno, presence: true, length: { is: 9} ,numericality: { only_integer: true} ,uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    def index
        @contacts = Contact.all
    end

    def new
      @con = Contact.new
    end

    def show

      @con  = Contact.find(params[:id])

    end

    def edit
      @con  = Contact.find(params[:id])
   
    end

    def update
      @con = Contact.find(params[:id])

      if @con.update(contact_params)
        redirect_to @con
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def create
  
        @con = Contact.new(contact_params)
        if @con.save
        
        redirect_to @con ,notice: "Contact Successfuly Created"
        else
        
          render :new, status: :unprocessable_entity
        end
    end



    def destroy

      @con = Contact.find(params[:id])
      @con.destroy
      redirect_to contacts_url ,notice: "Contact Successfuly Deleted"

    end
    
    private def contact_params
      params.require(:contact).permit(:firstname, :lastname ,:email ,:contactno)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


    def about
        @title = "About us"
    end

    def contactus
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/edit.html.erb
<h1> Edit User <%= @con.firstname %> <%= @con.lastname %> </h1>

<%= form_for :contact, url: contacts_path(@con),method: :patch do |f| %>


<div>
<%= f.label :Firstname %>
<%= f.text_field :firstname %>

   <% @con.errors.full_messages_for(:firstname).each do |message| %>
      <div><%= message %></div>
    <% end %>
 
</div>


<p>
<%= f.label :lastname %>
<%= f.text_field :lastname %>

  <% @con.errors.full_messages_for(:lastname).each do |message| %>
      <div><%= message %></div>
    <% end %>
</p>

<p>
<%= f.label :Email %>
 <%= f.text_field :email %>

   <% @con.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
</p>


<p>
<%= f.label :Contactno %>
 <%= f.text_field :contactno %>
   <% @con.errors.full_messages_for(:contactno).each do |message| %>
      <div><%= message %></div>
    <% end %>
</p>


<%= f.submit %>
<% end %>


 

app/views/contacts/index.html.erb
<h1 class="text-lg">Hello World! home page</h1>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<ul>
  <% @contacts.each do |contact| %>

  
    <li>
     

        <a href="/contacts/<%= contact.id %>">
        <%= contact.firstname %>   <%= contact.lastname %>
         </a>

          <a href="/contacts/<%= contact.id %>/edit">
      Edit
       </a> 


       
<%= link_to "Destroy", contact_path(contact), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

                  
                  </li>
    
  <% end %>
</ul>

app/views/contacts/new.html.erb
<h1> Add Contact</h1>


<%= form_for @con do |f| %>


<div>
<%= f.label :Firstname %>
<%= f.text_field :firstname %>

   <% @con.errors.full_messages_for(:firstname).each do |message| %>
      <div><%= message %></div>
    <% end %>
 
</div>


<p>
<%= f.label :lastname %>
<%= f.text_field :lastname %>

  <% @con.errors.full_messages_for(:lastname).each do |message| %>
      <div><%= message %></div>
    <% end %>
</p>

<p>
<%= f.label :Email %>
 <%= f.text_field :email %>

   <% @con.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
</p>


<p>
<%= f.label :Contactno %>
 <%= f.text_field :contactno %>
   <% @con.errors.full_messages_for(:contactno).each do |message| %>
      <div><%= message %></div>
    <% end %>
</p>


<%= f.submit %>
<% end %>


 

app/views/contacts/show.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<h1> <%= @con.firstname %> <%= @con.lastname %> </h1>
<h3> <%= @con.email %> <%= @con.contactno %> </h3><ul>


  <li><%= link_to "Edit", edit_contact_path(@con) %></li>
  <li><%= link_to "Destroy", contact_path(@con), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contactbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


 
    <%= javascript_importmap_tags %>
  </head>

  <body>





    
<h1 class="text-3xl font-bold underline">
    Contacts
</h1>
 
      <ul>
        <li class="nav-item">
              <%= link_to  "Home ", home_path  %>
        </li>
    
       <li class="nav-item">
       <%= link_to  "Create Contact ", new_contact_path  %> 
        </li>
      
     
      </ul>



    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> <%= @title    %> </h1>

app/views/pages/contactus.html.erb
<h1>Contact Us</h1>